services:
  database:
    container_name: wavydaves-postgres
    image: postgres
    user: 1000:1000
    environment:
      - POSTGRES_USER=WavyDaves
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=WavyDaves
    ports:
      - "5432:5432"
    volumes:
      - ./Database:/var/lib/postgresql/data
