services:
  database:
    container_name: wavydaves-postgres
    image: postgres
    environment:
      - POSTGRES_USER=WavyDaves
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=WavyDaves
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./Database:/var/lib/postgresql/data
